//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDePersistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class estilos
    {
        public estilos()
        {
            this.peliculas = new HashSet<peliculas>();
        }
    
        public string estilo { get; set; }
    
        public virtual ICollection<peliculas> peliculas { get; set; }
    }
}
