//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDePersistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class socios
    {
        public socios()
        {
            this.alquileres = new HashSet<alquileres>();
        }
    
        public int idSocio { get; set; }
        public string login { get; set; }
        public string pwd { get; set; }
        public string nombre { get; set; }
        public string apell1 { get; set; }
        public string apell2 { get; set; }
        public string direccion { get; set; }
        public string localidad { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<alquileres> alquileres { get; set; }
    }
}
